//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CETAPUtilities.Database
{
    using System;
    using System.Collections.Generic;

    public partial class Country
    {
        public int ISO { get; set; }
        public string Country1 { get; set; }
        public string Nationality { get; set; }
        public string ISO_2Alpha { get; set; }
        public string ISO_3Alpha { get; set; }
        public Nullable<int> ITU_Calling { get; set; }
        public byte[] Flag { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
