//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CETAPUtilities.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NBT_ProductionEntities : DbContext
    {
        public NBT_ProductionEntities()
            : base("name=NBT_ProductionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IntakeYear> IntakeYears { get; set; }
        public virtual DbSet<TestVenue> TestVenues { get; set; }
        public virtual DbSet<Classification> Classifications { get; set; }
        public virtual DbSet<ContactType> ContactTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<IDType> IDTypes { get; set; }
        public virtual DbSet<NBTAttendance> NBTAttendances { get; set; }
        public virtual DbSet<NBTStaffPayment> NBTStaffPayments { get; set; }
        public virtual DbSet<NBTStaffPosition> NBTStaffPositions { get; set; }
        public virtual DbSet<NBTStaffRate> NBTStaffRates { get; set; }
        public virtual DbSet<RegisteredEmployee> RegisteredEmployees { get; set; }
        public virtual DbSet<StaffContactDetail> StaffContactDetails { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<TestName> TestNames { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<Composit> Composits { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<InstitutionMatch> InstitutionMatches { get; set; }
    }
}
