//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CETAPUtilities.Database
{
    using System;
    using System.Collections.Generic;

    public partial class NBTStaffPayment
    {
        public int PaymentID { get; set; }
        public int StaffID { get; set; }
        public int PositionID { get; set; }
        public int AttendanceID { get; set; }
        public System.DateTime DOT { get; set; }
        public int VenueCode { get; set; }
        public int DaysHours { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.Guid RowGUID { get; set; }

        public virtual TestVenue TestVenue { get; set; }
        public virtual NBTAttendance NBTAttendance { get; set; }
        public virtual NBTStaffPosition NBTStaffPosition { get; set; }
        public virtual RegisteredEmployee RegisteredEmployee { get; set; }
    }
}
